services:
  redis:
    image: redis:latest
    deploy:
      resources:
        limits:
          memory: 500M

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      deploy:
      resources:
        limits:
          memory: 500M

  nginx:
    image: nginx:latest
    entrypoint: /usr/sbin/nginx-debug
    command: 
      - "-g"
      - "daemon off;"
    configs:
      - source: my_config_2
        target: /etc/nginx/conf.d/default.conf
    deploy:
      resources:
        limits:
          memory: 4000M


  worker:
    image: uffizzitest/worker:latest
    deploy:
      resources:
        limits:
          memory: 2000M

  vote:
    image: uffizzitest/vote:latest
    deploy:
      resources:
        limits:
          memory: 500M


  result:
    image: uffizzitest/result:latest
    deploy:
      resources:
        limits:
          memory: 500M


configs:
  my_config_2:
    file: ./config2/vote2.conf


x-uffizzi-ingress:
  service: nginx
  port: 8080
